# Prepping Cleaned Data for Classification and Regression Modeling
In this notebook we will pull in the movie dataset that was created in the **Movies_Data_Cleaning** notebook. This notebook will focus on preparing the data for modeling in both our classification and regression models in order to properly predict the financial success of movies

DATA DICTIONARY: https://github.com/hudsop2/ai_academy_capstone?tab=readme-ov-file#data-dictionary

As always we start by loading in our libraries and our dataset.

In [1]:
# load pandas library
# load OneHotEncoder library
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
# load complete movies dataset
movies_data = pd.read_csv('movies_complete.csv')
movies_data.head()

,movie_title,release_date,month_released,rated,genre,runtime_minutes,belongs_to_collection,tagline,production_budget_usd,domestic_gross_usd,...,dir_producer,dir_production_designer,dir_production_manager,dir_script_dept,dir_sound_dept,dir_soundtrack,dir_special_effects,dir_stunts,dir_visual_effects,dir_writer
0,The Shining,1980-05-22,5,R,Drama,146.0,0,A masterpiece of modern horror.,19000000,44568631,...,1,0,0,0,0,0,0,0,0,1
1,The Blue Lagoon,1980-07-05,6,R,Adventure,104.0,1,A sensuous story of natural love.,4500000,47923795,...,0,0,0,0,0,0,0,0,0,1
2,Airplane!,1980-07-02,7,PG,Comedy,88.0,1,"What's slower than a speeding bullet, and able...",3500000,83453539,...,0,0,0,0,0,0,0,0,0,0
3,Caddyshack,1980-07-25,7,R,Comedy,98.0,1,The snobs against the slobs!,6000000,39846344,...,1,0,0,0,0,0,0,0,0,1
4,Friday the 13th,1980-05-09,5,R,Horror,95.0,1,They were warned...They are doomed...And on Fr...,550000,39754601,...,1,0,0,0,0,0,0,0,0,1

# Section 1: Preparing the Data for Modeling
This section largely consists of reorganizing fields and completing the finishing touches before we begin modeling with our data.

We begin by creating a couple of new fields **non_dom_gross_usd** which could be used as a post-production target. And **title_length** which focuses on the character length of the movie title.

In [4]:
# create new column for non-domestic (US) gross income
# create new column for lenght of movie title
movies_data['non_dom_gross_usd'] = movies_data['worldwide_gross_usd'] - movies_data['domestic_gross_usd']
movies_data['title_length'] = movies_data['movie_title'].apply(lambda x: len(x))
pd.set_option('display.max_columns', None)
movies_data.head()

,movie_title,release_date,month_released,rated,genre,runtime_minutes,belongs_to_collection,tagline,production_budget_usd,domestic_gross_usd,worldwide_gross_usd,imdb_score,dir_acted,dir_animation_dept,dir_art_dept,dir_art_dir,dir_assistant_dir,dir_camera_dept,dir_casting_dept,dir_casting_dir,dir_cinematographer,dir_composer,dir_costume_designer,dir_editor,dir_editorial_dept,dir_location_management,dir_makeup_dept,dir_music_artist,dir_music_dept,dir_producer,dir_production_designer,dir_production_manager,dir_script_dept,dir_sound_dept,dir_soundtrack,dir_special_effects,dir_stunts,dir_visual_effects,dir_writer,non_dom_gross_usd,title_length
0,The Shining,1980-05-22,5,R,Drama,146.0,0,A masterpiece of modern horror.,19000000,44568631,45613093,8.4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1044462,11
1,The Blue Lagoon,1980-07-05,6,R,Adventure,104.0,1,A sensuous story of natural love.,4500000,47923795,47923795,5.8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,15
2,Airplane!,1980-07-02,7,PG,Comedy,88.0,1,"What's slower than a speeding bullet, and able...",3500000,83453539,83453539,7.7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9
3,Caddyshack,1980-07-25,7,R,Comedy,98.0,1,The snobs against the slobs!,6000000,39846344,39849764,7.3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,3420,10
4,Friday the 13th,1980-05-09,5,R,Horror,95.0,1,They were warned...They are doomed...And on Fr...,550000,39754601,59754601,6.4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,20000000,15

Here we use all of our gross income (USD) columns to generate ROI (return on investment) for each film, globally, domestically, and non-domestically.

In [5]:
# create roi columns for each gross_usd column
movies_data['worldwide_roi'] = (movies_data['worldwide_gross_usd'] - movies_data['production_budget_usd']) / movies_data['production_budget_usd']
movies_data['domestic_roi'] = (movies_data['domestic_gross_usd'] - movies_data['production_budget_usd']) / movies_data['production_budget_usd']
movies_data['non_dom_roi'] = (movies_data['non_dom_gross_usd'] - movies_data['production_budget_usd']) / movies_data['production_budget_usd']
movies_data.head()

,movie_title,release_date,month_released,rated,genre,runtime_minutes,belongs_to_collection,tagline,production_budget_usd,domestic_gross_usd,worldwide_gross_usd,imdb_score,dir_acted,dir_animation_dept,dir_art_dept,dir_art_dir,dir_assistant_dir,dir_camera_dept,dir_casting_dept,dir_casting_dir,dir_cinematographer,dir_composer,dir_costume_designer,dir_editor,dir_editorial_dept,dir_location_management,dir_makeup_dept,dir_music_artist,dir_music_dept,dir_producer,dir_production_designer,dir_production_manager,dir_script_dept,dir_sound_dept,dir_soundtrack,dir_special_effects,dir_stunts,dir_visual_effects,dir_writer,non_dom_gross_usd,title_length,worldwide_roi,domestic_roi,non_dom_roi
0,The Shining,1980-05-22,5,R,Drama,146.0,0,A masterpiece of modern horror.,19000000,44568631,45613093,8.4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1044462,11,1.400689,1.345717,-0.945028
1,The Blue Lagoon,1980-07-05,6,R,Adventure,104.0,1,A sensuous story of natural love.,4500000,47923795,47923795,5.8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,15,9.649732,9.649732,-1.000000
2,Airplane!,1980-07-02,7,PG,Comedy,88.0,1,"What's slower than a speeding bullet, and able...",3500000,83453539,83453539,7.7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9,22.843868,22.843868,-1.000000
3,Caddyshack,1980-07-25,7,R,Comedy,98.0,1,The snobs against the slobs!,6000000,39846344,39849764,7.3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,3420,10,5.641627,5.641057,-0.999430
4,Friday the 13th,1980-05-09,5,R,Horror,95.0,1,They were warned...They are doomed...And on Fr...,550000,39754601,59754601,6.4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,20000000,15,107.644729,71.281093,35.363636

Looking at some potential outliers within the data, these movies are some of the worst performing in the entire dataset.

In [6]:
print(movies_data[movies_data['worldwide_roi'] < -0.90])

                      movie_title release_date  month_released  rated  \
13                  Heaven's Gate   1980-11-19              11      R
14              Raise the Titanic   1980-01-01               8     PG
17           Can't Stop the Music   1980-06-20               6     PG
43     The Pursuit of D.B. Cooper   1981-11-13              11     PG
87    Once Upon a Time in America   1984-02-16               6      R
...                           ...          ...             ...    ...
2817          Beasts of No Nation   2015-09-11              10  TV-MA
2829                   By the Sea   2015-11-12              11      R
2852                      Cop Car   2015-08-07               8      R
2985                   Mr. Church   2016-09-16               9  PG-13
3018              Berlin Syndrome   2017-05-25               4      R

          genre  runtime_minutes  belongs_to_collection  \
13    Adventure            219.0                      0
14       Action            115.0                      0
17    Biography            124.0                      0
43    Adventure            100.0                      0
87        Crime            229.0                      0
...         ...              ...                    ...
2817      Drama            137.0                      0
2829      Drama            122.0                      0
2852      Crime             88.0                      0
2985     Comedy            104.0                      0
3018      Drama            116.0                      0

                                                tagline  \
13    The only thing greater than their passion for ...
14    They've found the Titanic. There's just one th...
17                The Musical Comedy Smash of the 80's!
43                 Who says you can't take it with you?
87    Crime, passion and lust for power - Sergio Leo...
...                                                 ...
2817                            Child. Captive. Killer.
2829                                                NaN
2852             Their first drive could be their last.
2985   He was the one person she could always count on.
3018                                                NaN

      production_budget_usd  domestic_gross_usd  worldwide_gross_usd  \
13                 44000000             3484331              3484523
14                 40000000             7000000              7000000
17                 20000000             2000000              2000000
43                 12000000             2104164              2104164
87                 30000000             5321508              5576072
...                     ...                 ...                  ...
2817                6000000               90777                90777
2829               20000000              538460              3727746
2852                5000000              134552               143658
2985                8000000              685780               685780
3018                5500000               28660               788191

      imdb_score  dir_acted  dir_animation_dept  dir_art_dept  dir_art_dir  \
13           6.8          0                   0             0            0
14           5.0          0                   0             0            0
17           4.2          1                   0             0            0
43           5.6          0                   0             0            0
87           8.4          0                   0             0            0
...          ...        ...                 ...           ...          ...
2817         7.7          0                   0             0            0
2829         5.3          1                   0             0            0
2852         6.3          0                   0             0            0
2985         7.7          0                   0             0            0
3018         6.3          0                   0             0            0

      dir_assistant_dir  dir_camera_dept  dir_casting_dept  dir_casting_dir  \
13                    0                0                 0                0
14                    0                0                 0                0
17                    0                0                 0                0
43                    0                0                 0                0
87                    1                0                 0                0
...                 ...              ...               ...              ...
2817                  0                0                 0                0
2829                  0                0                 0                0
2852                  0                0                 0                0
2985                  0                0                 0                0
3018                  0                0                 0                0

      dir_cinematographer  dir_composer  dir_costume_designer  dir_editor  \
13                      0             0                     0           0
14                      0             0                     0           0
17                      0             0                     0           0
43                      0             0                     0           0
87                      0             0                     0           0
...                   ...           ...                   ...         ...
2817                    0             0                     0           0
2829                    0             0                     0           0
2852                    0             0                     0           0
2985                    0             0                     0           0
3018                    0             0                     0           0

      dir_editorial_dept  dir_location_management  dir_makeup_dept  \
13                     0                        0                0
14                     1                        0                0
17                     0                        0                0
43                     0                        0                0
87                     0                        0                0
...                  ...                      ...              ...
2817                   0                        0                0
2829                   0                        0                0
2852                   0                        0                0
2985                   0                        0                0
3018                   0                        0                0

      dir_music_artist  dir_music_dept  dir_producer  dir_production_designer  \
13                   0               0             1                        0
14                   0               0             1                        0
17                   0               0             0                        0
43                   0               0             0                        0
87                   0               0             0                        0
...                ...             ...           ...                      ...
2817                 0               0             1                        0
2829                 0               0             1                        0
2852                 0               0             1                        0
2985                 0               0             1                        0
3018                 0               0             0                        0

      dir_production_manager  dir_script_dept  dir_sound_dept  dir_soundtrack  \
13                         0                0               0               0
14                         0                0               0               0
17                         0                0               0               1
43                         0                0               0               0
87                         0                0               0               0
...                      ...              ...             ...             ...
2817                       0                0               0               0
2829                       0                0               0               0
2852                       0                0               0               0
2985                       0                0               0               0
3018                       0                0               0               0

      dir_special_effects  dir_stunts  dir_visual_effects  dir_writer  \
13                      0           0                   0           1
14                      0           0                   0           0
17                      0           0                   0           0
43                      0           0                   0           0
87                      0           0                   0           1
...                   ...         ...                 ...         ...
2817                    0           0                   0           1
2829                    0           0                   0           0
2852                    0           0                   0           1
2985                    0           0                   0           1
3018                    0           0                   0           1

      non_dom_gross_usd  title_length  worldwide_roi  domestic_roi  \
13                  192            13      -0.920806     -0.920811
14                    0            17      -0.825000     -0.825000
17                    0            20      -0.900000     -0.900000
43                    0            26      -0.824653     -0.824653
87               254564            27      -0.814131     -0.822616
...                 ...           ...            ...           ...
2817                  0            19      -0.984870     -0.984870
2829            3189286            10      -0.813613     -0.973077
2852               9106             7      -0.971268     -0.973090
2985                  0            10      -0.914277     -0.914277
3018             759531            15      -0.856693     -0.994789

      non_dom_roi
13      -0.999996
14      -1.000000
17      -1.000000
43      -1.000000
87      -0.991515
...           ...
2817    -1.000000
2829    -0.840536
2852    -0.998179
2985    -1.000000
3018    -0.861903

[108 rows x 44 columns]

We create our classification variable here **success_level_ww**, a value of 1 means that the film made it's money back or profited. A value of 0 means the film didn't make it's production budget back. This variable will be what we use as our target variable during classification modeling.

In [6]:
# formula for categorizing success levels of movies based on worlwide roi
movies_data['success_level_ww'] = movies_data['worldwide_roi'].apply(lambda x: 0 if x<0 else 1)

In [7]:
movies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3058 entries, 0 to 3057
Data columns (total 45 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   movie_title              3058 non-null   object
 1   release_date             3058 non-null   object
 2   month_released           3058 non-null   int64
 3   rated                    3054 non-null   object
 4   genre                    3058 non-null   object
 5   runtime_minutes          3058 non-null   float64
 6   belongs_to_collection    3058 non-null   int64
 7   tagline                  2805 non-null   object
 8   production_budget_usd    3058 non-null   int64
 9   domestic_gross_usd       3058 non-null   int64
 10  worldwide_gross_usd      3058 non-null   int64
 11  imdb_score               3058 non-null   float64
 12  dir_acted                3058 non-null   int64
 13  dir_animation_dept       3058 non-null   int64
 14  dir_art_dept             3058 non-null   int64
 15  dir_art_dir              3058 non-null   int64
 16  dir_assistant_dir        3058 non-null   int64
 17  dir_camera_dept          3058 non-null   int64
 18  dir_casting_dept         3058 non-null   int64
 19  dir_casting_dir          3058 non-null   int64
 20  dir_cinematographer      3058 non-null   int64
 21  dir_composer             3058 non-null   int64
 22  dir_costume_designer     3058 non-null   int64
 23  dir_editor               3058 non-null   int64
 24  dir_editorial_dept       3058 non-null   int64
 25  dir_location_management  3058 non-null   int64
 26  dir_makeup_dept          3058 non-null   int64
 27  dir_music_artist         3058 non-null   int64
 28  dir_music_dept           3058 non-null   int64
 29  dir_producer             3058 non-null   int64
 30  dir_production_designer  3058 non-null   int64
 31  dir_production_manager   3058 non-null   int64
 32  dir_script_dept          3058 non-null   int64
 33  dir_sound_dept           3058 non-null   int64
 34  dir_soundtrack           3058 non-null   int64
 35  dir_special_effects      3058 non-null   int64
 36  dir_stunts               3058 non-null   int64
 37  dir_visual_effects       3058 non-null   int64
 38  dir_writer               3058 non-null   int64
 39  non_dom_gross_usd        3058 non-null   int64
 40  title_length             3058 non-null   int64
 41  worldwide_roi            3058 non-null   float64
 42  domestic_roi             3058 non-null   float64
 43  non_dom_roi              3058 non-null   float64
 44  success_level_ww         3058 non-null   int64
dtypes: float64(5), int64(35), object(5)
memory usage: 1.1+ MB

These columns can be dropped as they don't help in modeling since they aren't quantifiable or categorical. The amount of TV-MA movies is insignificant so we get rid of that category as well.

In [8]:
# drop columns unnecessary for modeling
movies_data.drop(['tagline', 'movie_title', 'release_date'], axis=1, inplace=True)
movies_data = movies_data[movies_data['rated'] != 'TV-MA']
movies_data.dropna(inplace=True)
movies_data.reset_index(drop=True, inplace=True)
movies_data.head()

,month_released,rated,genre,runtime_minutes,belongs_to_collection,production_budget_usd,domestic_gross_usd,worldwide_gross_usd,imdb_score,dir_acted,dir_animation_dept,dir_art_dept,dir_art_dir,dir_assistant_dir,dir_camera_dept,dir_casting_dept,dir_casting_dir,dir_cinematographer,dir_composer,dir_costume_designer,dir_editor,dir_editorial_dept,dir_location_management,dir_makeup_dept,dir_music_artist,dir_music_dept,dir_producer,dir_production_designer,dir_production_manager,dir_script_dept,dir_sound_dept,dir_soundtrack,dir_special_effects,dir_stunts,dir_visual_effects,dir_writer,non_dom_gross_usd,title_length,worldwide_roi,domestic_roi,non_dom_roi,success_level_ww
0,5,R,Drama,146.0,0,19000000,44568631,45613093,8.4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1044462,11,1.400689,1.345717,-0.945028,1
1,6,R,Adventure,104.0,1,4500000,47923795,47923795,5.8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,15,9.649732,9.649732,-1.000000,1
2,7,PG,Comedy,88.0,1,3500000,83453539,83453539,7.7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9,22.843868,22.843868,-1.000000,1
3,7,R,Comedy,98.0,1,6000000,39846344,39849764,7.3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,3420,10,5.641627,5.641057,-0.999430,1
4,5,R,Horror,95.0,1,550000,39754601,59754601,6.4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,20000000,15,107.644729,71.281093,35.363636,1

In [9]:
movies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3052 entries, 0 to 3051
Data columns (total 42 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   month_released           3052 non-null   int64
 1   rated                    3052 non-null   object
 2   genre                    3052 non-null   object
 3   runtime_minutes          3052 non-null   float64
 4   belongs_to_collection    3052 non-null   int64
 5   production_budget_usd    3052 non-null   int64
 6   domestic_gross_usd       3052 non-null   int64
 7   worldwide_gross_usd      3052 non-null   int64
 8   imdb_score               3052 non-null   float64
 9   dir_acted                3052 non-null   int64
 10  dir_animation_dept       3052 non-null   int64
 11  dir_art_dept             3052 non-null   int64
 12  dir_art_dir              3052 non-null   int64
 13  dir_assistant_dir        3052 non-null   int64
 14  dir_camera_dept          3052 non-null   int64
 15  dir_casting_dept         3052 non-null   int64
 16  dir_casting_dir          3052 non-null   int64
 17  dir_cinematographer      3052 non-null   int64
 18  dir_composer             3052 non-null   int64
 19  dir_costume_designer     3052 non-null   int64
 20  dir_editor               3052 non-null   int64
 21  dir_editorial_dept       3052 non-null   int64
 22  dir_location_management  3052 non-null   int64
 23  dir_makeup_dept          3052 non-null   int64
 24  dir_music_artist         3052 non-null   int64
 25  dir_music_dept           3052 non-null   int64
 26  dir_producer             3052 non-null   int64
 27  dir_production_designer  3052 non-null   int64
 28  dir_production_manager   3052 non-null   int64
 29  dir_script_dept          3052 non-null   int64
 30  dir_sound_dept           3052 non-null   int64
 31  dir_soundtrack           3052 non-null   int64
 32  dir_special_effects      3052 non-null   int64
 33  dir_stunts               3052 non-null   int64
 34  dir_visual_effects       3052 non-null   int64
 35  dir_writer               3052 non-null   int64
 36  non_dom_gross_usd        3052 non-null   int64
 37  title_length             3052 non-null   int64
 38  worldwide_roi            3052 non-null   float64
 39  domestic_roi             3052 non-null   float64
 40  non_dom_roi              3052 non-null   float64
 41  success_level_ww         3052 non-null   int64
dtypes: float64(5), int64(35), object(2)
memory usage: 1001.6+ KB

In [10]:
movies_data.describe()

,month_released,runtime_minutes,belongs_to_collection,production_budget_usd,domestic_gross_usd,worldwide_gross_usd,imdb_score,dir_acted,dir_animation_dept,dir_art_dept,dir_art_dir,dir_assistant_dir,dir_camera_dept,dir_casting_dept,dir_casting_dir,dir_cinematographer,dir_composer,dir_costume_designer,dir_editor,dir_editorial_dept,dir_location_management,dir_makeup_dept,dir_music_artist,dir_music_dept,dir_producer,dir_production_designer,dir_production_manager,dir_script_dept,dir_sound_dept,dir_soundtrack,dir_special_effects,dir_stunts,dir_visual_effects,dir_writer,non_dom_gross_usd,title_length,worldwide_roi,domestic_roi,non_dom_roi,success_level_ww
count,3052.000000,3052.000000,3052.000000,3.052000e+03,3.052000e+03,3.052000e+03,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000,3.052000e+03,3052.000000,3052.000000,3052.000000,3052.000000,3052.000000
mean,7.224771,109.765400,0.237221,4.326873e+07,5.896281e+07,1.277828e+08,6.453702,0.261468,0.015072,0.007864,0.001311,0.033421,0.014744,0.000328,0.000328,0.029489,0.007208,0.000655,0.028178,0.007864,0.000328,0.000983,0.001311,0.008847,0.749672,0.008191,0.001311,0.003604,0.001638,0.025557,0.001638,0.004915,0.013106,0.634993,6.881996e+07,14.273263,3.164903,1.423253,0.741650,0.760813
std,3.358694,19.099697,0.425449,4.450519e+07,7.277113e+07,1.940581e+08,0.979309,0.439506,0.121860,0.088343,0.036185,0.179762,0.120548,0.018101,0.018101,0.169200,0.084610,0.025595,0.165509,0.088343,0.018101,0.031342,0.036185,0.093655,0.433273,0.090149,0.036185,0.059936,0.040449,0.157835,0.040449,0.069945,0.113748,0.481511,1.285219e+08,7.329849,13.393465,8.485351,5.857552,0.426657
min,1.000000,63.000000,0.000000,5.000000e+04,3.200000e+03,7.396000e+03,1.900000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,1.000000,-0.996791,-0.999893,-1.000000,0.000000
25%,4.000000,96.000000,0.000000,1.400000e+07,1.436988e+07,2.119101e+07,5.900000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.490597e+06,9.000000,0.036621,-0.410469,-0.888616,1.000000
50%,8.000000,106.000000,0.000000,3.000000e+07,3.561602e+07,5.944108e+07,6.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.154881e+07,13.000000,1.206077,0.182957,-0.200153,1.000000
75%,10.000000,120.000000,0.000000,5.800000e+07,7.387863e+07,1.531462e+08,7.100000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,7.747655e+07,18.000000,3.063191,1.219101,0.921004,1.000000
max,12.000000,271.000000,1.000000,3.650000e+08,7.852216e+08,2.923706e+09,9.300000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.138484e+09,50.000000,415.564740,233.231832,187.920640,1.000000

In [15]:
movies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3052 entries, 0 to 3051
Data columns (total 42 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   month_released           3052 non-null   int64
 1   rated                    3052 non-null   object
 2   genre                    3052 non-null   object
 3   runtime_minutes          3052 non-null   float64
 4   belongs_to_collection    3052 non-null   int64
 5   production_budget_usd    3052 non-null   int64
 6   domestic_gross_usd       3052 non-null   int64
 7   worldwide_gross_usd      3052 non-null   int64
 8   imdb_score               3052 non-null   float64
 9   dir_acted                3052 non-null   int64
 10  dir_animation_dept       3052 non-null   int64
 11  dir_art_dept             3052 non-null   int64
 12  dir_art_dir              3052 non-null   int64
 13  dir_assistant_dir        3052 non-null   int64
 14  dir_camera_dept          3052 non-null   int64
 15  dir_casting_dept         3052 non-null   int64
 16  dir_casting_dir          3052 non-null   int64
 17  dir_cinematographer      3052 non-null   int64
 18  dir_composer             3052 non-null   int64
 19  dir_costume_designer     3052 non-null   int64
 20  dir_editor               3052 non-null   int64
 21  dir_editorial_dept       3052 non-null   int64
 22  dir_location_management  3052 non-null   int64
 23  dir_makeup_dept          3052 non-null   int64
 24  dir_music_artist         3052 non-null   int64
 25  dir_music_dept           3052 non-null   int64
 26  dir_producer             3052 non-null   int64
 27  dir_production_designer  3052 non-null   int64
 28  dir_production_manager   3052 non-null   int64
 29  dir_script_dept          3052 non-null   int64
 30  dir_sound_dept           3052 non-null   int64
 31  dir_soundtrack           3052 non-null   int64
 32  dir_special_effects      3052 non-null   int64
 33  dir_stunts               3052 non-null   int64
 34  dir_visual_effects       3052 non-null   int64
 35  dir_writer               3052 non-null   int64
 36  non_dom_gross_usd        3052 non-null   int64
 37  title_length             3052 non-null   int64
 38  worldwide_roi            3052 non-null   float64
 39  domestic_roi             3052 non-null   float64
 40  non_dom_roi              3052 non-null   float64
 41  success_level_ww         3052 non-null   int64
dtypes: float64(5), int64(35), object(2)
memory usage: 1001.6+ KB

Our data modeling prep is complete and we can save our dataset so that it can be loaded into our next notebook.

In [16]:
# save the completed dataframe as a csv to be used later in modeling
movies_data.to_csv('movies_modeling.csv', index=False)

# Conclusion
In this notebook we pulled in the movie dataset that was created in the **Movies_Data_Cleaning** notebook. And finished preparing the data for modeling in both our classification and regression models in order to properly predict the financial success of movies. The dataset from this notebook will be used in both the **Regression_Model** notebook and **Classification_Model** notebook.